/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Task status enumeration
 */
export enum TaskStatus {
  PENDING = 'pending',
  IN_PROGRESS = 'in_progress', 
  COMPLETED = 'completed',
  FAILED = 'failed',
  CANCELLED = 'cancelled',
  BLOCKED = 'blocked'
}

/**
 * Task priority levels
 */
export enum TaskPriority {
  LOW = 1,
  MEDIUM = 2,
  HIGH = 3,
  CRITICAL = 4
}

/**
 * Validation methods for goal verification
 */
export enum ValidationMethod {
  LLM_EVALUATION = 'llm_evaluation',
  TOOL_EXECUTION = 'tool_execution',
  FILE_VERIFICATION = 'file_verification',
  TEST_EXECUTION = 'test_execution',
  MANUAL = 'manual'
}

/**
 * Success criteria for goal validation
 */
export interface SuccessCriteria {
  /** Description of what constitutes success */
  description: string;
  /** Specific conditions to check */
  conditions: string[];
  /** Validation data or context */
  validationContext?: Record<string, unknown>;
}

/**
 * Goal definition with success criteria
 */
export interface Goal {
  /** Unique goal identifier */
  id: string;
  /** Human-readable goal description */
  description: string;
  /** Success criteria for this goal */
  successCriteria: SuccessCriteria;
  /** How to validate this goal */
  validationMethod: ValidationMethod;
  /** Whether this goal has been achieved */
  achieved: boolean;
  /** Validation result details */
  validationResult?: {
    success: boolean;
    details: string;
    timestamp: Date;
  };
}

/**
 * Individual subtask within a larger task
 */
export interface SubTask {
  /** Unique subtask identifier */
  id: string;
  /** Parent task ID */
  parentTaskId: string;
  /** Human-readable subtask description */
  description: string;
  /** Current status */
  status: TaskStatus;
  /** Progress percentage (0-100) */
  progress: number;
  /** Task dependencies (other subtask IDs) */
  dependencies: string[];
  /** Required tools for this subtask */
  requiredTools: string[];
  /** Estimated execution time in milliseconds */
  estimatedDuration?: number;
  /** Actual execution time in milliseconds */
  actualDuration?: number;
  /** Priority level */
  priority: TaskPriority;
  /** Error information if failed */
  error?: {
    message: string;
    details?: string;
    timestamp: Date;
    retryCount: number;
  };
  /** Execution context and parameters */
  context?: Record<string, unknown>;
  /** Start time */
  startedAt?: Date;
  /** Completion time */
  completedAt?: Date;
}

/**
 * Main task definition
 */
export interface Task {
  /** Unique task identifier */
  id: string;
  /** Human-readable task description */
  description: string;
  /** Goals to be achieved by this task */
  goals: Goal[];
  /** Subtasks that comprise this task */
  subtasks: SubTask[];
  /** External dependencies (other task IDs) */
  dependencies: string[];
  /** Current status */
  status: TaskStatus;
  /** Overall progress percentage (0-100) */
  progress: number;
  /** Estimated total execution time in milliseconds */
  estimatedDuration?: number;
  /** Actual total execution time in milliseconds */
  actualDuration?: number;
  /** Priority level */
  priority: TaskPriority;
  /** Creation timestamp */
  createdAt: Date;
  /** Start timestamp */
  startedAt?: Date;
  /** Completion timestamp */
  completedAt?: Date;
  /** User who created the task */
  createdBy?: string;
  /** Task metadata and context */
  metadata: {
    /** Original user request that generated this task */
    originalRequest: string;
    /** Conversation context when task was created */
    conversationContext?: string;
    /** Project context information */
    projectContext?: {
      workingDirectory: string;
      gitBranch?: string;
      openFiles?: string[];
    };
    /** Custom metadata */
    custom?: Record<string, unknown>;
  };
  /** Error information if task failed */
  error?: {
    message: string;
    details?: string;
    timestamp: Date;
    failedSubtaskId?: string;
  };
}

/**
 * Task execution plan generated by the planner
 */
export interface TaskPlan {
  /** Unique plan identifier */
  id: string;
  /** Main task this plan executes */
  task: Task;
  /** Execution strategy */
  strategy: {
    /** Whether subtasks can be executed in parallel */
    allowParallelExecution: boolean;
    /** Maximum number of parallel subtasks */
    maxParallelTasks: number;
    /** Resource allocation strategy */
    resourceAllocation: 'balanced' | 'priority_based' | 'sequential';
    /** Retry configuration */
    retryPolicy: {
      maxRetries: number;
      backoffMultiplier: number;
      retryableErrors: string[];
    };
  };
  /** Dependency graph for execution ordering */
  dependencyGraph: {
    [subtaskId: string]: string[];
  };
  /** Resource requirements and estimates */
  resourceEstimates: {
    totalTokens: number;
    totalDuration: number;
    toolsRequired: string[];
    memoryRequirement: number;
  };
  /** Plan creation timestamp */
  createdAt: Date;
  /** Plan status */
  status: 'draft' | 'approved' | 'executing' | 'completed' | 'failed';
}

/**
 * Task execution context passed to tools and services
 */
export interface TaskExecutionContext {
  /** Current task being executed */
  task: Task;
  /** Current subtask being executed */
  currentSubtask?: SubTask;
  /** Execution plan */
  plan: TaskPlan;
  /** Session identifier */
  sessionId: string;
  /** Execution start time */
  executionStartTime: Date;
  /** Resource limits */
  resourceLimits: {
    maxTokens?: number;
    maxDuration?: number;
    maxMemoryMB?: number;
  };
  /** Callback functions for progress reporting */
  callbacks: {
    onProgress?: (progress: number, subtaskId?: string) => void;
    onSubtaskComplete?: (subtaskId: string, result: unknown) => void;
    onError?: (error: Error, subtaskId?: string) => void;
  };
}

/**
 * Result of task planning
 */
export interface TaskPlanningResult {
  /** Generated plan */
  plan: TaskPlan;
  /** Planning confidence score (0-1) */
  confidence: number;
  /** Planning warnings or recommendations */
  warnings: string[];
  /** Alternative strategies considered */
  alternatives?: Array<{
    description: string;
    pros: string[];
    cons: string[];
  }>;
}

/**
 * Task execution result
 */
export interface TaskExecutionResult {
  /** Whether the task completed successfully */
  success: boolean;
  /** Final task state */
  task: Task;
  /** Execution summary */
  summary: {
    totalDuration: number;
    completedSubtasks: number;
    failedSubtasks: number;
    goalsAchieved: number;
    resourcesUsed: {
      tokens: number;
      toolCalls: number;
      memoryMB: number;
    };
  };
  /** Detailed results from each subtask */
  subtaskResults: Array<{
    subtaskId: string;
    result: unknown;
    error?: Error;
  }>;
  /** Overall error if task failed */
  error?: Error;
}